/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class JDlgEd_Produtos extends javax.swing.JDialog {

    /**
     * Creates new form JDlgEd_Produtos
     */
    public JDlgEd_Produtos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Produtos");
        setLocationRelativeTo(null);
        desabilitar();
    }

    public void habilitar() {
        jTxtEd_Codigo.setEnabled(true);
        jTxtEd_Nome.setEnabled(true);
        jTxtEd_PrecoVenda.setEnabled(true);
        jTxtEd_EstoqueAtual.setEnabled(true);
        jTxtEd_DataValidade.setEnabled(true);
        jTxtPrecoPromocional.setEnabled(true);
        
        jCboEd_Promocao.setEnabled(true);
        
        jBtnEd_Confirmar.setEnabled(true);
        jBtnEd_Cancelar.setEnabled(true);
        
        jBtnEd_Alterar.setEnabled(false);
        jBtnEd_Incluir.setEnabled(false);
        jBtnEd_Pesquisar.setEnabled(false);
        jBtnEd_Excluir.setEnabled(false);
    }
    
    public void desabilitar() {
        jTxtEd_Codigo.setEnabled(false);
        jTxtEd_Nome.setEnabled(false);
        jTxtEd_PrecoVenda.setEnabled(false);
        jTxtEd_EstoqueAtual.setEnabled(false);
        jTxtEd_DataValidade.setEnabled(false);
        jTxtPrecoPromocional.setEnabled(false);
        
        jCboEd_Promocao.setEnabled(false);
        
        jBtnEd_Confirmar.setEnabled(false);
        jBtnEd_Cancelar.setEnabled(false);
        
        jBtnEd_Alterar.setEnabled(true);
        jBtnEd_Incluir.setEnabled(true);
        jBtnEd_Pesquisar.setEnabled(true);
        jBtnEd_Excluir.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnEd_Incluir = new javax.swing.JButton();
        jBtnEd_Alterar = new javax.swing.JButton();
        jBtnEd_Cancelar = new javax.swing.JButton();
        jBtnEd_Excluir = new javax.swing.JButton();
        jBtnEd_Pesquisar = new javax.swing.JButton();
        jBtnEd_Confirmar = new javax.swing.JButton();
        jTxtEd_Codigo = new javax.swing.JTextField();
        jLblNome = new javax.swing.JLabel();
        jTxtEd_Nome = new javax.swing.JTextField();
        jLblCodigo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtEd_EstoqueAtual = new javax.swing.JTextField();
        jTxtEd_DataValidade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtEd_PrecoVenda = new javax.swing.JTextField();
        jTxtPrecoPromocional = new javax.swing.JTextField();
        jCboEd_Promocao = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtnEd_Incluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnEd_Incluir.setText("Incluir");
        jBtnEd_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEd_IncluirActionPerformed(evt);
            }
        });

        jBtnEd_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnEd_Alterar.setText("Alterar");
        jBtnEd_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEd_AlterarActionPerformed(evt);
            }
        });

        jBtnEd_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnEd_Cancelar.setText("Cancelar");
        jBtnEd_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEd_CancelarActionPerformed(evt);
            }
        });

        jBtnEd_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnEd_Excluir.setText("Excluir");
        jBtnEd_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEd_ExcluirActionPerformed(evt);
            }
        });

        jBtnEd_Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnEd_Pesquisar.setText("Pesquisar");
        jBtnEd_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEd_PesquisarActionPerformed(evt);
            }
        });

        jBtnEd_Confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jBtnEd_Confirmar.setText("Confirmar");
        jBtnEd_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEd_ConfirmarActionPerformed(evt);
            }
        });

        jLblNome.setText("Nome");

        jLblCodigo.setText("Código");

        jLabel1.setText("Estoque atual");

        jLabel2.setText("Data de Validade");

        jLabel3.setText("Preco de Venda");

        jLabel4.setText("Preco Promocional");

        jLabel5.setText("Promocao");

        jTxtEd_PrecoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEd_PrecoVendaActionPerformed(evt);
            }
        });

        jCboEd_Promocao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnEd_Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnEd_Incluir))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnEd_Cancelar)
                            .addComponent(jBtnEd_Alterar))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnEd_Pesquisar)
                            .addComponent(jBtnEd_Excluir)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLblCodigo)
                            .addComponent(jTxtEd_Codigo)
                            .addComponent(jLabel1)
                            .addComponent(jTxtEd_EstoqueAtual)
                            .addComponent(jLabel3)
                            .addComponent(jTxtEd_PrecoVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLblNome)
                            .addComponent(jTxtEd_DataValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTxtEd_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(62, 62, 62))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTxtPrecoPromocional)
                                            .addGap(19, 19, 19)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jCboEd_Promocao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCodigo)
                    .addComponent(jLblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtEd_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtEd_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtEd_EstoqueAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtEd_DataValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtEd_PrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtPrecoPromocional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboEd_Promocao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnEd_Incluir)
                    .addComponent(jBtnEd_Alterar)
                    .addComponent(jBtnEd_Excluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnEd_Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnEd_Cancelar)
                    .addComponent(jBtnEd_Pesquisar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnEd_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEd_IncluirActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_jBtnEd_IncluirActionPerformed

    private void jBtnEd_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEd_AlterarActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_jBtnEd_AlterarActionPerformed

    private void jBtnEd_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEd_CancelarActionPerformed
        // TODO add your handling code here:
        desabilitar();
    }//GEN-LAST:event_jBtnEd_CancelarActionPerformed

    private void jBtnEd_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEd_ExcluirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "confirma exclusão?", "Selecione uma opção", JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_jBtnEd_ExcluirActionPerformed

    private void jBtnEd_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEd_PesquisarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showInputDialog(null, "entre com a chave primária:");
    }//GEN-LAST:event_jBtnEd_PesquisarActionPerformed

    private void jBtnEd_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEd_ConfirmarActionPerformed
        // TODO add your handling code here:
        desabilitar();
    }//GEN-LAST:event_jBtnEd_ConfirmarActionPerformed

    private void jTxtEd_PrecoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEd_PrecoVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEd_PrecoVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgEd_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgEd_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgEd_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgEd_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgEd_Produtos dialog = new JDlgEd_Produtos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnEd_Alterar;
    private javax.swing.JButton jBtnEd_Cancelar;
    private javax.swing.JButton jBtnEd_Confirmar;
    private javax.swing.JButton jBtnEd_Excluir;
    private javax.swing.JButton jBtnEd_Incluir;
    private javax.swing.JButton jBtnEd_Pesquisar;
    private javax.swing.JComboBox<String> jCboEd_Promocao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLblCodigo;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JTextField jTxtEd_Codigo;
    private javax.swing.JTextField jTxtEd_DataValidade;
    private javax.swing.JTextField jTxtEd_EstoqueAtual;
    private javax.swing.JTextField jTxtEd_Nome;
    private javax.swing.JTextField jTxtEd_PrecoVenda;
    private javax.swing.JTextField jTxtPrecoPromocional;
    // End of variables declaration//GEN-END:variables
}
