/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class JDlgEd_Cliente extends javax.swing.JDialog {

    /**
     * Creates new form JDlgEd_Cliente
     */
    public JDlgEd_Cliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Clientes");
        setLocationRelativeTo(null);
        
        // Estado inicial da tela (tudo desabilitado para edição)
        jTxtEd_Codigo.setEnabled(false);
        jTxtEd_Nome.setEnabled(false);
        jTxtEd_Cpf.setEnabled(false);
        jTxtEd_Rg.setEnabled(false);
        jCboEd_Sexo.setEnabled(false);
        jTxtEd_Email.setEnabled(false);
        jTxtEd_Telefone.setEnabled(false);
        jTxtEd_Celular.setEnabled(false);
        jTxtEd_Cep.setEnabled(false);
        jTxtEd_Logradouro.setEnabled(false);
        jTxtEd_Numero.setEnabled(false);
        jTxtEd_Estado.setEnabled(false);
        jTxtEd_Cidade.setEnabled(false);
        jTxtEd_Bairro.setEnabled(false);
        jTxtEd_Datadecadastro.setEnabled(false);
        jCboEd_Ativo.setEnabled(false);
        jCheckBox1.setEnabled(false); // Incluído conforme sua lista
        
        // Botões de confirmação desabilitados
        jBtnEd_Confirmar.setEnabled(false);
        jBtnEd_Cancelar.setEnabled(false);
    }

    public void habilitar() {
        // Habilita os campos de entrada
        jTxtEd_Codigo.setEnabled(true);
        jTxtEd_Nome.setEnabled(true);
        jTxtEd_Cpf.setEnabled(true);
        jTxtEd_Rg.setEnabled(true);
        jCboEd_Sexo.setEnabled(true);
        jTxtEd_Email.setEnabled(true);
        jTxtEd_Telefone.setEnabled(true);
        jTxtEd_Celular.setEnabled(true);
        jTxtEd_Cep.setEnabled(true);
        jTxtEd_Logradouro.setEnabled(true);
        jTxtEd_Numero.setEnabled(true);
        jTxtEd_Estado.setEnabled(true);
        jTxtEd_Cidade.setEnabled(true);
        jTxtEd_Bairro.setEnabled(true);
        jTxtEd_Datadecadastro.setEnabled(true);
        jCboEd_Ativo.setEnabled(true);
        jCheckBox1.setEnabled(true);
        
        // Habilita botões de salvar/cancelar
        jBtnEd_Confirmar.setEnabled(true);
        jBtnEd_Cancelar.setEnabled(true);
        
        // Desabilita botões de ação principal
        jBtnEd_Alterar.setEnabled(false);
        jBtnEd_Incluir.setEnabled(false);
        jBtnEd_Pesquisar.setEnabled(false);
        jBtnEd_Excluir.setEnabled(false);
    }
    
    public void desabilitar() {
        // Desabilita os campos de entrada
        jTxtEd_Codigo.setEnabled(false);
        jTxtEd_Nome.setEnabled(false);
        jTxtEd_Cpf.setEnabled(false);
        jTxtEd_Rg.setEnabled(false);
        jCboEd_Sexo.setEnabled(false);
        jTxtEd_Email.setEnabled(false);
        jTxtEd_Telefone.setEnabled(false);
        jTxtEd_Celular.setEnabled(false);
        jTxtEd_Cep.setEnabled(false);
        jTxtEd_Logradouro.setEnabled(false);
        jTxtEd_Numero.setEnabled(false);
        jTxtEd_Estado.setEnabled(false);
        jTxtEd_Cidade.setEnabled(false);
        jTxtEd_Bairro.setEnabled(false);
        jTxtEd_Datadecadastro.setEnabled(false);
        jCboEd_Ativo.setEnabled(false);
        jCheckBox1.setEnabled(false);
        
        // Desabilita botões de salvar/cancelar
        jBtnEd_Confirmar.setEnabled(false);
        jBtnEd_Cancelar.setEnabled(false);
        
        // Habilita botões de ação principal
        jBtnEd_Alterar.setEnabled(true);
        jBtnEd_Incluir.setEnabled(true);
        jBtnEd_Pesquisar.setEnabled(true);
        jBtnEd_Excluir.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jBtnEd_Cancelar = new javax.swing.JButton();
        jBtnEd_Excluir = new javax.swing.JButton();
        jBtnEd_Pesquisar = new javax.swing.JButton();
        jBtnEd_Confirmar = new javax.swing.JButton();
        jBtnEd_Incluir = new javax.swing.JButton();
        jBtnEd_Alterar = new javax.swing.JButton();
        jTxtEd_Codigo = new javax.swing.JTextField();
        jLblNome = new javax.swing.JLabel();
        jTxtEd_Nome = new javax.swing.JTextField();
        jLblCodigo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTxtEd_Cpf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtEd_Rg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCboEd_Sexo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTxtEd_Email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTxtEd_Telefone = new javax.swing.JTextField();
        jTxtEd_Celular = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTxtEd_Cep = new javax.swing.JTextField();
        jTxtEd_Logradouro = new javax.swing.JTextField();
        jTxtEd_Numero = new javax.swing.JTextField();
        jTxtEd_Estado = new javax.swing.JTextField();
        jTxtEd_Cidade = new javax.swing.JTextField();
        jTxtEd_Bairro = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTxtEd_Datadecadastro = new javax.swing.JTextField();
        jCboEd_Ativo = new javax.swing.JComboBox<>();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtnEd_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnEd_Cancelar.setText("Cancelar");
        jBtnEd_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEd_CancelarActionPerformed(evt);
            }
        });

        jBtnEd_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnEd_Excluir.setText("Excluir");
        jBtnEd_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEd_ExcluirActionPerformed(evt);
            }
        });

        jBtnEd_Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnEd_Pesquisar.setText("Pesquisar");
        jBtnEd_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEd_PesquisarActionPerformed(evt);
            }
        });

        jBtnEd_Confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jBtnEd_Confirmar.setText("Confirmar");
        jBtnEd_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEd_ConfirmarActionPerformed(evt);
            }
        });

        jBtnEd_Incluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnEd_Incluir.setText("Incluir");
        jBtnEd_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEd_IncluirActionPerformed(evt);
            }
        });

        jBtnEd_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnEd_Alterar.setText("Alterar");
        jBtnEd_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEd_AlterarActionPerformed(evt);
            }
        });

        jLblNome.setText("Nome");

        jLblCodigo.setText("Código");

        jLabel1.setText("CPF");

        jTxtEd_Cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEd_CpfActionPerformed(evt);
            }
        });

        jLabel2.setText("RG");

        jLabel3.setText("Sexo");

        jCboEd_Sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Outro" }));
        jCboEd_Sexo.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jCboEd_SexoComponentHidden(evt);
            }
        });
        jCboEd_Sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboEd_SexoActionPerformed(evt);
            }
        });

        jLabel4.setText("Email");

        jTxtEd_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEd_EmailActionPerformed(evt);
            }
        });

        jLabel5.setText("Telefone Fixo");

        jLabel6.setText("Celular");

        jLabel7.setText("CEP");

        jLabel8.setText("Logradouro");

        jLabel9.setText("Numero");

        jLabel10.setText("Bairro");

        jLabel11.setText("Cidade");

        jLabel12.setText("Estado");

        jTxtEd_Cep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEd_CepActionPerformed(evt);
            }
        });

        jTxtEd_Estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEd_EstadoActionPerformed(evt);
            }
        });

        jLabel13.setText("Data de Cadastro");

        jLabel14.setText("Ativo");

        jTxtEd_Datadecadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEd_DatadecadastroActionPerformed(evt);
            }
        });

        jCboEd_Ativo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnEd_Incluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnEd_Alterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnEd_Excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnEd_Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnEd_Cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnEd_Pesquisar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblCodigo)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jTxtEd_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTxtEd_Rg, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTxtEd_Codigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                            .addComponent(jLabel13)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTxtEd_Datadecadastro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                .addComponent(jTxtEd_Bairro, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTxtEd_Cep, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTxtEd_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblNome)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(jTxtEd_Cpf)
                                    .addComponent(jTxtEd_Telefone)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel11)
                                    .addComponent(jTxtEd_Logradouro)
                                    .addComponent(jTxtEd_Cidade, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9)
                                    .addComponent(jCboEd_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jTxtEd_Celular)
                                    .addComponent(jLabel12)
                                    .addComponent(jTxtEd_Numero)
                                    .addComponent(jTxtEd_Estado, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)))
                            .addComponent(jLabel14)
                            .addComponent(jCboEd_Ativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCodigo)
                    .addComponent(jLblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTxtEd_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtEd_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtEd_Cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtEd_Rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCboEd_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtEd_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtEd_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtEd_Celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtEd_Logradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtEd_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTxtEd_Cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtEd_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtEd_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtEd_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtEd_Datadecadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboEd_Ativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnEd_Incluir)
                    .addComponent(jBtnEd_Alterar)
                    .addComponent(jBtnEd_Excluir)
                    .addComponent(jBtnEd_Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnEd_Cancelar)
                    .addComponent(jBtnEd_Pesquisar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    private void jBtnEd_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEd_CancelarActionPerformed
        // TODO add your handling code here:
        desabilitar();
    }//GEN-LAST:event_jBtnEd_CancelarActionPerformed

    private void jBtnEd_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEd_ExcluirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "confirma exclusão?", "Selecione uma opção", JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_jBtnEd_ExcluirActionPerformed

    private void jBtnEd_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEd_PesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnEd_PesquisarActionPerformed

    private void jBtnEd_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEd_ConfirmarActionPerformed
        // TODO add your handling code here:
        desabilitar();
    }//GEN-LAST:event_jBtnEd_ConfirmarActionPerformed

    private void jBtnEd_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEd_IncluirActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_jBtnEd_IncluirActionPerformed

    private void jBtnEd_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEd_AlterarActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_jBtnEd_AlterarActionPerformed

    private void jTxtEd_CpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEd_CpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEd_CpfActionPerformed

    private void jCboEd_SexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboEd_SexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboEd_SexoActionPerformed

    private void jCboEd_SexoComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jCboEd_SexoComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboEd_SexoComponentHidden

    private void jTxtEd_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEd_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEd_EmailActionPerformed

    private void jTxtEd_CepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEd_CepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEd_CepActionPerformed

    private void jTxtEd_EstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEd_EstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEd_EstadoActionPerformed

    private void jTxtEd_DatadecadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEd_DatadecadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEd_DatadecadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgEd_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgEd_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgEd_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgEd_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgEd_Cliente dialog = new JDlgEd_Cliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnEd_Alterar;
    private javax.swing.JButton jBtnEd_Cancelar;
    private javax.swing.JButton jBtnEd_Confirmar;
    private javax.swing.JButton jBtnEd_Excluir;
    private javax.swing.JButton jBtnEd_Incluir;
    private javax.swing.JButton jBtnEd_Pesquisar;
    private javax.swing.JComboBox<String> jCboEd_Ativo;
    private javax.swing.JComboBox<String> jCboEd_Sexo;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLblCodigo;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JTextField jTxtEd_Bairro;
    private javax.swing.JTextField jTxtEd_Celular;
    private javax.swing.JTextField jTxtEd_Cep;
    private javax.swing.JTextField jTxtEd_Cidade;
    private javax.swing.JTextField jTxtEd_Codigo;
    private javax.swing.JTextField jTxtEd_Cpf;
    private javax.swing.JTextField jTxtEd_Datadecadastro;
    private javax.swing.JTextField jTxtEd_Email;
    private javax.swing.JTextField jTxtEd_Estado;
    private javax.swing.JTextField jTxtEd_Logradouro;
    private javax.swing.JTextField jTxtEd_Nome;
    private javax.swing.JTextField jTxtEd_Numero;
    private javax.swing.JTextField jTxtEd_Rg;
    private javax.swing.JTextField jTxtEd_Telefone;
    // End of variables declaration//GEN-END:variables
}
