/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author u07880060103
 */
public class JFrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmPrincipal
     */
    public JFrmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Menu Principal");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMnuPrincipal = new javax.swing.JMenuBar();
        jMnuCadastros = new javax.swing.JMenu();
        jMnuEd_Usuarios = new javax.swing.JMenuItem();
        jMnuEd_Clientes = new javax.swing.JMenuItem();
        jMnuEd_Fornecedor = new javax.swing.JMenuItem();
        jMnuEd_Produtos = new javax.swing.JMenuItem();
        jMnuEd_Sabores = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuSair = new javax.swing.JMenuItem();
        jMnuMovimentos = new javax.swing.JMenu();
        jMnuVendas = new javax.swing.JMenuItem();
        jMnuCompras = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMnuCadastros.setMnemonic('c');
        jMnuCadastros.setText("Cadastros");

        jMnuEd_Usuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuEd_Usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/man.png"))); // NOI18N
        jMnuEd_Usuarios.setMnemonic('u');
        jMnuEd_Usuarios.setText("Usuários");
        jMnuEd_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuEd_UsuariosActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMnuEd_Usuarios);

        jMnuEd_Clientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuEd_Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente.png"))); // NOI18N
        jMnuEd_Clientes.setMnemonic('c');
        jMnuEd_Clientes.setText("Clientes");
        jMnuEd_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuEd_ClientesActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMnuEd_Clientes);

        jMnuEd_Fornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuEd_Fornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fornecedor.jpg"))); // NOI18N
        jMnuEd_Fornecedor.setText("Fornecedor");
        jMnuEd_Fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuEd_FornecedorActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMnuEd_Fornecedor);

        jMnuEd_Produtos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuEd_Produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Produto.png"))); // NOI18N
        jMnuEd_Produtos.setText("Produtos");
        jMnuEd_Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuEd_ProdutosActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMnuEd_Produtos);

        jMnuEd_Sabores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMnuEd_Sabores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sabor.png"))); // NOI18N
        jMnuEd_Sabores.setText("Sabores");
        jMnuEd_Sabores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuEd_SaboresActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMnuEd_Sabores);
        jMnuCadastros.add(jSeparator1);

        jMnuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        jMnuSair.setMnemonic('s');
        jMnuSair.setText("Sair");
        jMnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuSairActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMnuSair);

        jMnuPrincipal.add(jMnuCadastros);

        jMnuMovimentos.setMnemonic('m');
        jMnuMovimentos.setText("Movimentos");

        jMnuVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuVendas.setMnemonic('v');
        jMnuVendas.setText("Vendas");
        jMnuVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendasActionPerformed(evt);
            }
        });
        jMnuMovimentos.add(jMnuVendas);

        jMnuCompras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMnuCompras.setMnemonic('c');
        jMnuCompras.setText("Compras");
        jMnuMovimentos.add(jMnuCompras);

        jMnuPrincipal.add(jMnuMovimentos);

        setJMenuBar(jMnuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuEd_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuEd_UsuariosActionPerformed
        // TODO add your handling code here:
        JDlgEd_Usuarios jDlgMpvUsuarios = new JDlgEd_Usuarios(null, true);
        jDlgMpvUsuarios.setVisible(true);
    }//GEN-LAST:event_jMnuEd_UsuariosActionPerformed

    private void jMnuVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuVendasActionPerformed

    private void jMnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMnuSairActionPerformed

    private void jMnuEd_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuEd_ClientesActionPerformed
        // TODO add your handling code here:
        JDlgEd_Cliente jDlgMpvCliente = new JDlgEd_Cliente(null, true);
        jDlgMpvCliente.setVisible(true);
    }//GEN-LAST:event_jMnuEd_ClientesActionPerformed

    private void jMnuEd_FornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuEd_FornecedorActionPerformed
        // TODO add your handling code here:
        JDlgEd_Fornecedor jDlgMpvFornecedor = new JDlgEd_Fornecedor(null, true);
        jDlgMpvFornecedor.setVisible(true);
    }//GEN-LAST:event_jMnuEd_FornecedorActionPerformed

    private void jMnuEd_ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuEd_ProdutosActionPerformed
        // TODO add your handling code here:
        JDlgEd_Produtos jDlgMpvProdutos = new JDlgEd_Produtos(null, true);
        jDlgMpvProdutos.setVisible(true);
    }//GEN-LAST:event_jMnuEd_ProdutosActionPerformed

    private void jMnuEd_SaboresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuEd_SaboresActionPerformed
        // TODO add your handling code here:
        JDlgEd_Sabores jDlgMpvSabores = new JDlgEd_Sabores(null, true);
        jDlgMpvSabores.setVisible(true);
    }//GEN-LAST:event_jMnuEd_SaboresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMnuCadastros;
    private javax.swing.JMenuItem jMnuCompras;
    private javax.swing.JMenuItem jMnuEd_Clientes;
    private javax.swing.JMenuItem jMnuEd_Fornecedor;
    private javax.swing.JMenuItem jMnuEd_Produtos;
    private javax.swing.JMenuItem jMnuEd_Sabores;
    private javax.swing.JMenuItem jMnuEd_Usuarios;
    private javax.swing.JMenu jMnuMovimentos;
    private javax.swing.JMenuBar jMnuPrincipal;
    private javax.swing.JMenuItem jMnuSair;
    private javax.swing.JMenuItem jMnuVendas;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
